config/routes.rb
Rails.application.routes.draw do
 post 'voto/create'

  root 'home#index'

  resources :receitas do
    get :clonar, on: :member
  end

  resources :categorias

  devise_for :usuarios

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_and_belongs_to_many :receita
end

app/models/receita.rb
class Receita < ActiveRecord::Base
  has_and_belongs_to_many :categorias

  belongs_to :usuario

  validates :titulo, presence: true, length: { maximum: 255 }
  validates :descricao, presence: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :receitas
end

app/models/voto.rb
class Voto < ActiveRecord::Base
  belongs_to :receita
  belongs_to :categoria
  belongs_to :usuario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nome
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:password, :password_confirmation, :current_password, :nome) }
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:nome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @receitas = Receita.page(params[:page])
  end
end

app/controllers/receitas_controller.rb
class ReceitasController < ApplicationController
  before_action :set_receita, only: [:show, :clonar, :destroy]

  before_action :authenticate_usuario!

  # GET /receitas
  # GET /receitas.json
  def index
    @receitas = Receita.all
    @receitas = current_usuario.receitas.page(params[:page])
  end

  # GET /receitas/1
  # GET /receitas/1.json
  def show
  end

  # GET /receitas/new
  def new
    @receita = current_usuario.receitas.new
  end

  # GET /receitas/1/clonar
  def clonar
    categorias = @receita.categorias.collect { |e| e.id }
    @receita = current_usuario.receitas.new(@receita.attributes)
    @receita.id = nil
    @receita.cloned_from_id = params[:id]
    @receita.categoria_ids = categorias
  end

  # POST /receitas
  # POST /receitas.json
  def create
    @receita = current_usuario.receitas.new(receita_params)

    respond_to do |format|
      if @receita.save
        format.html { redirect_to @receita, notice: 'Receita cadastrada com sucesso.' }
        format.json { render :show, status: :created, location: @receita }
      else
        format.html { render :new }
        format.json { render json: @receita.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /receitas/1
  # DELETE /receitas/1.json
  def destroy
    @receita.destroy
    respond_to do |format|
      format.html { redirect_to receitas_url, notice: 'Receita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receita
      @receita = current_usuario.receitas.find(params[:id]) if usuario_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receita_params
      params.require(:receita).permit(:cloned_from_id, :titulo, :descricao, categoria_ids: [])
    end
end

app/controllers/voto_controller.rb
class VotoController < ApplicationController
  def create
    voto = Voto.new(usuario: current_usuario)
    voto.receita = Receita.find(params[:receita_id])
    voto.categoria = Categoria.find(params[:categoria_id])
    voto.like = params[:tipo]
    voto.save

    respond_to do |format|
      if voto.save
        session[:already_voted] = voto.receita_id
        format.html { redirect_to voto.receita, notice: 'Seu voto foi computado' }
      else
        format.html { redirect_to voto.receita, notice: 'Não foi possivel computar seu voto' }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/helpers/version_helper.rb
module VersionHelper
  MAJOR = 0
  MINOR = 1
  TINY  = 0
  PRE   = "beta"

  def app_version
    [MAJOR, MINOR, TINY, PRE].compact.join(".").to_s  
  end
end

app/helpers/voto_helper.rb
module VotoHelper
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/index.html.erb
<h1>Listing categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorias.each do |categoria| %>
      <tr>
        <td><%= categoria.nome %></td>
        <td><%= link_to 'Show', categoria %></td>
        <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
        <td><%= link_to 'Destroy', categoria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria', new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @categoria.nome %>
</p>

<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>

app/views/home/index.html.erb
<div class="row">
  <% @receitas.each do |receita| %>
    <div class="col-sm-12">
      <h3><%= link_to receita.titulo, receita_path(receita) %></h3>
      <%= raw(receita.descricao.gsub(/\n/,',&nbsp;')[0..100]) %>...<br>
    </div>
  <% end %>
</div>

<%= paginate @receitas %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EquipeHetfield</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-primary navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toque para navegar</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Receitas Online</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Receitas', root_path %></li>
        <%- if usuario_signed_in? -%>
        <li><%= link_to 'Minhas Receitas', receitas_path %></li>
        <li><%= link_to 'Nova Receitas', new_receita_path %></li>
        <%- end -%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <%- if usuario_signed_in? -%>
        <li><p class="navbar-text"><%= current_usuario.nome %></p></li>
        <li><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %></li>
      <%- else -%>
        <li><%= link_to 'Entrar', usuario_session_path %></li>
        <li><%= link_to 'Cadastrar-se', new_usuario_registration_path %></li>
      <%- end -%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <div class="container-wrapper">
    <main class="main">
      <%= yield %>
    </main>
  </div>
</div>

<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <strong>Versão:</strong> <%= app_version %>
      </div>
      <div class="col-sm-6 text-right">
        <p>Desenvolvido por equipe <strong>Hetfield</strong></p>
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/receitas/_form.html.erb
<%= form_for(@receita) do |f| %>
  <% if @receita.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receita.errors.count, "error") %> prohibited this receita from being saved:</h2>

      <ul>
      <% @receita.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :cloned_from_id %>
  <div class="field">
    <%= f.label :titulo, 'Título', class: 'form-label' %>
    <%= f.text_field :titulo, autofocus: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :descricao, 'Descrição', class: 'form-label' %>
    <%= f.text_area :descricao, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :categorias, class: 'form-label' %>
    <%= f.collection_check_boxes(:categoria_ids, Categoria.all, :id, :nome) do |b| %>
        <br> <%= b.label {b.check_box + b.object.nome}%>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar', class: 'btn btn-success' %>
    <%= link_to 'Cancelar', receitas_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/receitas/clonar.html.erb
<h1>Clonando Receita</h1>

<%= render 'form' %>

app/views/receitas/index.html.erb
<h1>Minhas Receitas</h1>

<% if @receitas.length == 0 %>
  
  <div class="alert alert-warning">
    Nenhuma receita foi cadastrada. Clique <%= link_to 'aqui', new_receita_path %> para cadastrar.
  </div>

<%- else -%>

  <div class="row">
    <% @receitas.each do |receita| %>
      <div class="col-sm-12">
        <h3><%= link_to receita.titulo, receita_path(receita) %></h3>
        
        <%= raw(receita.descricao) %><br>

        <%= link_to receita, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
          <i class="fa fa-trash-o"></i> 
          Apagar
        <%- end -%>
        <hr>
      </div>
    <% end %>
  </div>
  
<% end %>

<%= paginate @receitas %>

<br>

<%= link_to 'Nova Receita', new_receita_path, class: 'btn btn-default' %>

app/views/receitas/new.html.erb
<h1>Nova Receita</h1>

<%= render 'form' %>

app/views/receitas/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @receita.titulo %></h1>

<p><%= raw(@receita.descricao.gsub(/\n/,'<br>')) %></p>

<p>
  <strong>Categorias:</strong>
  <% @receita.categorias.each do |b| %>
      <br> <%= b.nome %>
          <% if usuario_signed_in?  && session[:already_voted] != @receita.id %>
             <%= button_to('Aprovar', {action: 'create', controller: :voto, receita_id: @receita.id,categoria_id: b.id, tipo: true}) +
                         button_to('Reprovar', {action: 'create', controller: :voto, receita_id: @receita.id, categoria_id: b.id, tipo: false})%>
          <%end%>
  <% end %>
</p>

<%= link_to 'Voltar', receitas_path, class: 'btn btn-default btn-xs' %>
<%- if usuario_signed_in? -%>
  <%= link_to clonar_receita_path(@receita), class: 'btn btn-default btn-xs' do %>
    <i class="fa fa-copy"></i> 
    Clonar Receita
  <%- end -%>
  <% if @receita.usuario.id == current_usuario.id %>
    <%= link_to @receita, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
      <i class="fa fa-trash-o"></i> 
      Apagar
    <%- end -%>
  <%- end -%>
<%- end -%>
<% if usuario_signed_in? && session[:already_voted] == @receita.id%>
    Positivos: <%= Voto.where(receita: @receita.id, like: true).all.size %>
    Negativo: <%= Voto.where(receita: @receita.id, like: false).all.size %>
<%end%>
<h1><%= @receita.titulo %></h1>
<h1><%= @receita.titulo %></h1>

app/views/voto/create.html.erb
<h1>Voto#create</h1>
<p>Find me in app/views/voto/create.html.erb</p>